import * as XLSX from 'xlsx';
import { ParsedFile } from '../types';
import { AppError } from '../utils/errors';
import { parsePdfGestor } from './pdfParser';

/**
 * Unified entry point: routes PDF files to the PDF parser and everything else
 * to the Excel/CSV parser. Drop-in replacement for parseFile.
 */
export async function parseFileOrPdf(buffer: Buffer, originalName: string): Promise<ParsedFile> {
  const ext = originalName.split('.').pop()?.toLowerCase();
  if (ext === 'pdf') {
    return parsePdfGestor(buffer, originalName);
  }
  return parseFile(buffer, originalName);
}

/**
 * Normalizes a string: trim + uppercase + remove accents
 */
export function normalize(val: string | number | null | undefined): string {
  if (val === null || val === undefined) return '';
  return String(val)
    .trim()
    .toUpperCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/\s+/g, ' '); // normalizes multiple spaces
}

/**
 * Parses an Excel or CSV buffer into rows of key-value pairs.
 * Tries multiple header rows (0, 1, 2, 3, 4, 5) to find the most columns.
 */
export function parseFile(buffer: Buffer, originalName: string): ParsedFile {
  let workbook: XLSX.WorkBook;
  try {
    workbook = XLSX.read(buffer, { type: 'buffer', cellDates: true });
  } catch (err) {
    throw new AppError('ERR_FILE_CORRUPT', `No se pudo leer el archivo ${originalName}. Formato dañado o inválido.`);
  }

  const sheetName = workbook.SheetNames[0];
  if (!sheetName) {
    throw new AppError('ERR_FILE_CORRUPT', `El archivo ${originalName} está vacío (no tiene hojas).`);
  }
  const sheet = workbook.Sheets[sheetName];

  let bestRows: Record<string, string>[] = [];
  let bestColumns: string[] = [];

  // Try header rows 0-10 to find the best parse (some files have many metadata rows before the real header)
  for (let headerRow = 0; headerRow <= 10; headerRow++) {
    try {
      const raw = XLSX.utils.sheet_to_json<Record<string, unknown>>(sheet, {
        defval: '',
        raw: false,
        dateNF: 'YYYY-MM-DD',
        range: headerRow,
      });

      if (raw.length === 0) continue;

      const cols = Object.keys(raw[0]);
      // Filter out "unnamed" columns (auto-generated by xlsx for empty headers)
      const validCols = cols.filter(
        (c) => !c.startsWith('__EMPTY') && c.trim() !== ''
      );

      const isDataLike = (col: string): boolean => {
        const c = col.trim();
        // Looks like a date: M/D/YY, MM/DD/YYYY, YYYY-MM-DD, etc.
        if (/^\d{1,4}[\/\-]\d{1,2}[\/\-]\d{2,4}$/.test(c)) return true;
        // Looks like a number or currency: 1318000.00, 1,318,000.00, .00
        if (/^[\d\.,]+$/.test(c)) return true;
        // Single letter or very short non-alpha string
        if (c.length <= 1) return true;
        return false;
      };
      
      const scoreColumns = (cols: string[]): number =>
        cols.reduce((s, c) => s + (isDataLike(c) ? 0 : 1), 0);

      const score = scoreColumns(validCols);
      if (score > scoreColumns(bestColumns)) {
        bestColumns = validCols;
        
        bestRows = raw.map((r) => {
          const out: Record<string, string> = {};
          for (const col of validCols) {
            const v = r[col];
            // keep value as is (trim if string), but without accents or weird encodings?
            // The requirement says "normalizar el valor", but doing it here might lose original case.
            // We just ensure it's a string. And we do rigorous normalize() later when matching.
            out[col] = v !== undefined && v !== null ? String(v).trim() : '';
          }
          return out;
        }).filter(r => {
          // Filtrar filas completamente vacías
          return Object.values(r).some(val => val !== '');
        });
      }
    } catch {
      // skip
    }
  }

  if (bestColumns.length === 0) {
    throw new AppError('ERR_FILE_CORRUPT', `El archivo ${originalName} no contiene columnas válidas detectables reconociendo datos.`);
  }

  return { rows: bestRows, columns: bestColumns };
}

/**
 * Finds the best matching column from a list of aliases
 */
export function findColumn(columns: string[], aliases: string[]): string | null {
  const normalizedCols = columns.map((c) => normalize(c));
  for (const alias of aliases) {
    const idx = normalizedCols.indexOf(normalize(alias));
    if (idx !== -1) return columns[idx];
  }
  return null;
}

/**
 * Formats a date string nicely
 */
export function formatDate(val: string): string {
  if (!val || val.trim() === '') return '';
  // Already formatted as YYYY-MM-DD from xlsx
  const d = new Date(val);
  if (isNaN(d.getTime())) return val;
  return d.toLocaleDateString('es-CO', {
    day: '2-digit',
    month: '2-digit',
    year: 'numeric',
  });
}
